---
- name: Create password directory
  file:
    path: "{{ passwd_dir }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '644'
  become: yes

- name: Add a line to a password file if the file does not exist (secret is --extra-var)
  lineinfile:
    path: "{{ passwd_dir }}/secret"
    line: "{{ secret }}"
    create: yes
  become: yes

- name: Setup new account
  shell: geth account new --password secret --datadir "{{ datadir }}"
  args:
    executable: /bin/bash

- debug:
    var: hostvars[groups['master'][0]].bootstrap_url

- name: Create executable starter of bootstrap node
  shell: |
    echo "#!/bin/bash" > "{{ home }}/{{ exec_script }}"
    echo -e "\n /usr/bin/geth --datadir {{ datadir }} --networkid {{ network_id }} --bootnodes {{ hostvars[groups['master'][0]].bootstrap_url }}" >> "{{ home }}/{{ exec_script }}"
  args:
    executable: /bin/bash

- name: Change mode and permissions of starter
  file:
    path: "{{ home }}/{{ exec_script }}"
    mode: '755'
    group: "{{ default_ssh_user }}"
    owner: "{{ default_ssh_user }}"
    state: file

- name: Create bootstrap node service
  template:
    src: geth-slave.service.j2
    dest: /etc/systemd/system/geth-slave.service
  become: yes
  notify:
    - reread configs 
    - start geth-slave