---
# write public address in file
- name: Setup new account
  shell: geth account new --password secret --datadir "{{ datadir }}"
  args:
    executable: /bin/bash

- debug:
    var: hostvars[groups['master'][0]].bootstrap_url

# create .sh to add in service
# JENKINS CHANGE IP ansible_default_ipv4.address
- name: Create executable starter of bootstrap node
  shell: |
    echo "#!/bin/bash" > "{{ home }}/{{ exec_script }}"
    echo -e "\n /usr/bin/geth --datadir {{ datadir }} --networkid {{ network_id }} --bootnodes {{ hostvars[groups['master'][0]].bootstrap_url }}" >> "{{ home }}/{{ exec_script }}"
  args:
    executable: /bin/bash

# change permissions
- name: Change mode and permissions of starter
  file:
    path: "{{ home }}/{{ exec_script }}"
    mode: '755'
    group: "{{ default_ssh_user }}"
    owner: "{{ default_ssh_user }}"
    state: file

# create service
- name: Create bootstrap node service
  template:
    src: geth-slave.service.j2
    dest: /etc/systemd/system/geth-slave.service
  become: yes
  notify:
    - reread configs 
    - start geth-slave
# geth --datadir data --networkid 10 --bootnodes enode://